name: release

on:
  release:
    types: published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get tag name
        id: tag
        run: echo ::set-output name=result::$(echo $GITHUB_REF | cut -d/ -f3)

      - name: Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" |docker login --username wnagele --password-stdin

      - name: Installation
        uses: crazy-max/ghaction-docker-buildx@master

      - name: Build
        run: |
          docker buildx build \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7 \
            -t wnagele/piaware:${{ steps.tag.outputs.result }} \
            --push .
